version: "2"
services:
  db:
    container_name: "zz-db"
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=zzdb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - zzdbnet
  app:
    container_name: "zz-app"
    environment:
      - JAVA_OPTS=-server -Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:+UseAdaptiveSizePolicy -XX:MaxMetaspaceSize=1024m -Djava.net.preferIPv4Stack=true  -Dfile.encoding=UTF-8
    build:
      context: .
    ports:
      - 8080:8080
      - 9990:9990
    depends_on:
      - db
    dns: 8.8.8.8
    networks:
      - zzdbnet
networks:
  zzdbnet:
    driver: bridge